[commands.general]
activate = "CTRL+ENTER"
snaps = "SNA"
ortho = "ORT"
undo = "U"
redo = "R"
selectbyradius = "SR" # QGIS select tool
selectbyfreehand = "SF" # QGIS select tool
selectbydistance = "SD" # QGIS select tool
selectbylocation = "SL" # QGIS select tool
selectbyvalue = "SV" # QGIS select tool
deselect = "ESCAPE" # QGIS deselect all features tool
save = "CTRL+S"
repeat = "ENTER;SPACE"
run = "ENTER;SPACE"

[commands.create]
arc = "A"
circle = "C"
ellipse = "EL"
line = "L"
pline = "PL"
point = "PO"
polygon = "PG"
rectangle = "REC"
square = "SQ"

[commands.modify]
breakatpoint = "BRP"
pedit = "PE"
flatten = "FLA" # not in menu
trim = "TR"
scale = "SC"
rotate = "RO"
pedit = "PE"
offset = "O"
move = "M" # not in menu
mirror = "MI"
matchprop = "MA" # not in menu
lengthen = "LEN"
join = "J" # not in menu
fillet = "F"
extend = "EX"
explode = "X" # not in menu
erase = "E" # not in menu
copy = "CO" # not in menu
chamfer = "CH"
break = "BR"
align = "AL"
stretch = "STR"
reverse = "RE" # not in menu
array = "ARR"
changelayer = "CHL" # not in menu

[commands.civil]
samplelines = "SLP"
sectionproject = "SEP"
profilesuperimposed = "PSU"
profilefromsurface = "PRS"
projecttoprofile = "PRP"
profilebylayout = "PRL"
profileoffset = "POF"
profileproject = "PPR"
alignmentoffset = "ALO"
alignment = "AFP"

[commands.civil.grading]
breakline = "BRL"
gradingregion = "GR"

[commands.civil.pipes]
createnetwork = "PIN"

[commands.panels]
volumesdash = "VOD"
properties = "PR" # QGIS Identify panel
gradingtemplates = "GTP"
profiles = "PRF"
sections = "SEC"
breaklineedit = "BED"
profileedit = "PED"
regionedit = "RED"

[commands.annotate]
revcloud = "RVC"
label = "LAB"
note = "NOT"
mtext = "MT"
list = "LS"

[commands.dimension]
dimaligned = "DAL"
dimangular = "DAN"
dimarc = "DAR"
dimcontinue = "DCO"
dimdiameter = "DDA"
dimlinear = "DLI"
dimradius = "DRA"

[commands.analyze]
lineinfo = "LCP"
measurearea = "AR" # QGIS measure tool
measureangle = "CGA" # QGIS measure tool
dist = "DI" # QGIS measure tool

[commands.display]
wipeout = "WIP"
isolate = "ISO"
unisolate = "UNI"
layerthaw = "LAT"
layerfreeze = "LAF"
hide = "HIO"
